### ISSUE TITLE
Configuration per YAML

### ISSUE THREAD

**Issue by hown3d** [hown3d/container-image-scanner#2]
Each Agent should be configurable by a YAML config file or command line flags.

YAML Structure could be smth like this:
```yaml
# Name of the cluster you are watching
name: "kubernetes cluster xyz"
# Type of fetcher runtime that is run on this agent
type: "kubernetes"
# Config should be a certain config for the fetcher
# Can be different depending on runtime type
config: {}
```

- [ ] Configurable YAML Structure
- [ ] Load Config based of runtime
